### ISSUE TITLE
Please make ISRadioButton public 

### ISSUE THREAD

**Issue by zzycami** [thegoal/ISRadioButton#8]
You should make the class public so that when other user use you framework can find you class!!
`public class  ISRadioButton: UIButton`

**Comment by thegoal** [comment]
Download latest project from git it contains the fix (don't use pods ) .

Sent from my iPhone

On 20-Jul-2016, at 2:05 PM, ??? <notifications@github.com<mailto:notifications@github.com>> wrote:

You should make the class public so that when other user use you framework can find you class!!
public class ISRadioButton: UIButton

##

**Comment by zzycami** [comment]
Ok, thank you. why not update your pod version.

**Comment by thegoal** [comment]
You welcome ,There is some reference issues while creating new version of pod, I will update readme after creating new pod.
